### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key 

### ISSUE THREAD

**Issue by yzyouzhang** [sasv-challenge/SASVC2022_Baseline#4]
I encounter the following error when I run `main.py` with the Baseline2 configuration.
> omegaconf.errors.ConfigAttributeError: Missing key 

There are in total three keys missing.
`min_req_mem`  `gradient_clip`  `reload_every_n_epoch`

I fixed these missing keys one by one by setting them to 0 or None.
I am curious what are the default values for these. Thank you very much.

**Comment by Jungjee** [comment]
Hello, yzyouzhang. 
Would you mind sharing your omegaconf and pytorchlighning versions?
In `omegaconf==2.0.6`, keys not specified have default value of `None`. 

For reference, default value is None for both `gradient_clip` and `reload_every_n_epoch`.

**Comment by yzyouzhang** [comment]
Hi Jungjee,
Thanks for your quick reply.
I used `omegaconf==2.1.1`. It works well when I change back to 2.0.6.

**Comment by Jungjee** [comment]
Thanks. Closing this now.
