### ISSUE TITLE
speaker_loss.weight is not in the model.

### ISSUE THREAD

**Issue by yzyouzhang** [sasv-challenge/SASVC2022_Baseline#5]
Thanks for your repo. I have successfully replicated the baseline2 performance.
I encounter the following messages when I run `python save_embeddings.py`. It did not crash the program but I wonder where is the second line printed from since I did not find it. I am also not sure if it will cause potential issues.
> Device: cuda
> speaker_loss.weight is not in the model.
> Getting embedgins from set trn...

Thanks.

**Comment by Jungjee** [comment]
Hi,
It is from using below code.
It's related to the output layer (the one with softmax non-linearity) and
causes no problems. 

https://github.com/sasv-challenge/SASVC2022_Baseline/blob/322f6c781e9e09c3544f3e4ed3494d8f8501db47/utils.py#L71
