### ISSUE TITLE
About the extracted embeddings.

### ISSUE THREAD

**Issue by ikou-austin** [sasv-challenge/SASVC2022_Baseline#7]
When we installed the git-lfs and step to pull the embeddings data, an error like:
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/sasv-challenge/SASVC2022_Baseline.git/info/lfs
```
was appeared.

What should I do? How can I download the embeddings data?

**Comment by Jungjee** [comment]
Hello @ikou-austin , currently, we used all quota for downloading the uploaded embeddings. 
For now, we recommend to extract yourself, using the provided `python save_embeddings.py` script. Identical speaker and spoofing embeddings will be extracted in hours using a GPU. 

In addition, we will keep this issue open and let you know when we extend data quota. Thanks:)

**Comment by sasv-challenge** [comment]
@ikou-austin you can download embeddings now

**Comment by ikou-austin** [comment]
Thank you! It works now.
